In [1]:
import numpy as np
import pandas as pd
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
df = pd.read_csv("cereals_data.csv")
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,25,2,1.0,1.00,27.753301
74,Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,25,1,1.0,1.00,51.592193
76,Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,25,1,1.0,0.75,36.187559

In [3]:
#1. Describe the schema of table 
df.describe(include='all')

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,77,77,77,77.000000,77.000000,77.000000,77.000000,77.000000,76.000000,76.000000,75.000000,77.000000,77.000000,77.000000,77.000000,77.000000
unique,77,7,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,100%_Bran,K,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,23,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,106.883117,2.545455,1.012987,159.675325,2.151948,14.802632,7.026316,98.666667,28.246753,2.207792,1.029610,0.821039,42.665705
std,NaN,NaN,NaN,19.484119,1.094790,1.006473,83.832295,2.383364,3.907326,4.378656,70.410636,22.342523,0.832524,0.150477,0.232716,14.047289
min,NaN,NaN,NaN,50.000000,1.000000,0.000000,0.000000,0.000000,5.000000,0.000000,15.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,NaN,NaN,NaN,100.000000,2.000000,0.000000,130.000000,1.000000,12.000000,3.000000,42.500000,25.000000,1.000000,1.000000,0.670000,33.174094
50%,NaN,NaN,NaN,110.000000,3.000000,1.000000,180.000000,2.000000,14.500000,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.400208
75%,NaN,NaN,NaN,110.000000,3.000000,2.000000,210.000000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.828392
max,NaN,NaN,NaN,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

In [4]:
#2. Create view name as see where users can not see type column [first run appropriate query then create view] 
see = df.copy()
see

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,25,2,1.0,1.00,27.753301
74,Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,25,1,1.0,1.00,51.592193
76,Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,25,1,1.0,0.75,36.187559

In [5]:
see.drop('type',axis=1,inplace=True)
see

,name,mfr,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Bran,N,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.0,0.75,39.106174
73,Trix,G,110,1,1,140,0.0,13.0,12.0,25.0,25,2,1.0,1.00,27.753301
74,Wheat_Chex,R,100,3,1,230,3.0,17.0,3.0,115.0,25,1,1.0,0.67,49.787445
75,Wheaties,G,100,3,1,200,3.0,17.0,3.0,110.0,25,1,1.0,1.00,51.592193
76,Wheaties_Honey_Gold,G,110,2,1,200,1.0,16.0,8.0,60.0,25,1,1.0,0.75,36.187559

In [6]:
#3. Rename the view as saw 
saw = see.copy(deep=True)
saw

,name,mfr,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Bran,N,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.0,0.75,39.106174
73,Trix,G,110,1,1,140,0.0,13.0,12.0,25.0,25,2,1.0,1.00,27.753301
74,Wheat_Chex,R,100,3,1,230,3.0,17.0,3.0,115.0,25,1,1.0,0.67,49.787445
75,Wheaties,G,100,3,1,200,3.0,17.0,3.0,110.0,25,1,1.0,1.00,51.592193
76,Wheaties_Honey_Gold,G,110,2,1,200,1.0,16.0,8.0,60.0,25,1,1.0,0.75,36.187559

In [7]:
#4. Count how many are cold cereals 
df['type'][df['type']=='C'].value_counts()

type
C    74
Name: count, dtype: int64

In [8]:
#5. Count how many cereals are kept in shelf 3 
df['shelf'][df['shelf']==3].value_counts()

shelf
3    36
Name: count, dtype: int64

In [9]:
#6. Arrange the table from high to low according to ratings 
df1 = df.copy(deep = True)
df2 = df1.sort_values('rating',ascending=False)
df2

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.00,0.50,93.704912
64,Shredded_Wheat_'n'Bran,N,C,90,3,0,0,4.0,19.0,0.0,140.0,0,1,1.00,0.67,74.472949
65,Shredded_Wheat_spoon_size,N,C,90,3,0,0,3.0,20.0,0.0,120.0,0,1,1.00,0.67,72.801787
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.00,0.33,68.402973
63,Shredded_Wheat,N,C,80,2,0,0,3.0,16.0,0.0,95.0,0,1,0.83,1.00,68.235885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,Cocoa_Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.00,1.00,22.736446
18,Count_Chocula,G,C,110,1,1,180,0.0,12.0,13.0,65.0,25,2,1.00,1.00,22.396513
35,Honey_Graham_Ohs,Q,C,120,1,2,220,1.0,12.0,11.0,45.0,25,2,1.00,1.00,21.871292
12,Cinnamon_Toast_Crunch,G,C,120,1,3,210,0.0,13.0,9.0,45.0,25,2,1.00,0.75,19.823573
10,Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12.0,35.0,25,2,1.00,0.75,18.042851

In [10]:
#7. Suggest some column/s which can be Primary key 
df.isnull().sum()

name        0
mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       1
sugars      1
potass      2
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [11]:
df.nunique()

name        77
mfr          7
type         2
calories    11
protein      6
fat          5
sodium      27
fiber       13
carbo       21
sugars      16
potass      35
vitamins     3
shelf        3
weight       7
cups        12
rating      77
dtype: int64

Therefore name or rating can be used as a primary key.

In [12]:
#8. Find average of calories of hot cereal and cold cereal in one query 
df.groupby('type').calories.mean()

type
C    107.162162
H    100.000000
Name: calories, dtype: float64

In [13]:
#9. List only those cereals whose name begins with B 
df[df.name.str.startswith('B')]

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
7,Basic_4,G,C,130,3,2,210,2.0,18.0,8.0,100.0,25,3,1.33,0.75,37.038562
8,Bran_Chex,R,C,90,2,1,200,4.0,15.0,6.0,125.0,25,1,1.00,0.67,49.120253
9,Bran_Flakes,P,C,90,3,0,210,5.0,13.0,5.0,190.0,25,3,1.00,0.67,53.313813

In [14]:
#10. List only those cereals whose name begins with F 
df[df.name.str.startswith('F')]

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
24,Froot_Loops,K,C,110,2,1,125,1.0,11.0,13.0,30.0,25,2,1.00,1.00,32.207582
25,Frosted_Flakes,K,C,110,1,0,200,1.0,14.0,11.0,25.0,25,1,1.00,0.75,31.435973
26,Frosted_Mini-Wheats,K,C,100,3,0,0,3.0,14.0,7.0,100.0,25,2,1.00,0.80,58.345141
27,"Fruit_&_Fibre_Dates,_Walnuts,_and_Oats",P,C,120,3,2,160,5.0,12.0,10.0,200.0,25,3,1.25,0.67,40.917047
28,Fruitful_Bran,K,C,120,3,0,240,5.0,14.0,12.0,190.0,25,3,1.33,0.67,41.015492
29,Fruity_Pebbles,P,C,110,1,1,135,0.0,13.0,12.0,25.0,25,2,1.00,0.75,28.025765

In [15]:
#11. List only those cereals whose name ends with s 
df[df.name.str.endswith('s')]

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
5,Apple_Cinnamon_Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,25,1,1.00,0.75,29.509541
6,Apple_Jacks,K,C,110,2,0,125,1.0,11.0,14.0,30.0,25,2,1.00,1.00,33.174094
9,Bran_Flakes,P,C,90,3,0,210,5.0,13.0,5.0,190.0,25,3,1.00,0.67,53.313813
11,Cheerios,G,C,110,6,2,290,2.0,17.0,1.0,105.0,25,1,1.00,1.25,50.764999
13,Clusters,G,C,110,3,2,140,2.0,13.0,7.0,105.0,25,3,1.00,0.50,40.400208
14,Cocoa_Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.00,1.00,22.736446
16,Corn_Flakes,K,C,100,2,0,290,1.0,21.0,2.0,35.0,25,1,1.00,1.00,45.863324
17,Corn_Pops,K,C,110,1,0,90,1.0,13.0,12.0,20.0,25,2,1.00,1.00,35.782791
22,Crispy_Wheat_&_Raisins,G,C,100,2,1,140,2.0,11.0,10.0,120.0,25,3,1.00,0.75,36.176196
24,Froot_Loops,K,C,110,2,1,125,1.0,11.0,13.0,30.0,25,2,1.00,1.00,32.207582
25,Frosted_Flakes,K,C,110,1,0,200,1.0,14.0,11.0,25.0,25,1,1.00,0.75,31.435973
26,Frosted_Mini-Wheats,K,C,100,3,0,0,3.0,14.0,7.0,100.0,25,2,1.00,0.80,58.345141
27,"Fruit_&_Fibre_Dates,_Walnuts,_and_Oats",P,C,120,3,2,160,5.0,12.0,10.0,200.0,25,3,1.25,0.67,40.917047
29,Fruity_Pebbles,P,C,110,1,1,135,0.0,13.0,12.0,25.0,25,2,1.00,0.75,28.025765
31,Golden_Grahams,G,C,110,1,1,280,0.0,15.0,9.0,45.0,25,2,1.00,0.75,23.804043
32,Grape_Nuts_Flakes,P,C,100,3,1,140,3.0,15.0,5.0,85.0,25,3,1.00,0.88,52.076897
33,Grape-Nuts,P,C,110,3,0,170,3.0,17.0,3.0,90.0,25,3,1.00,0.25,53.371007
35,Honey_Graham_Ohs,Q,C,120,1,2,220,1.0,12.0,11.0,45.0,25,2,1.00,1.00,21.871292
36,Honey_Nut_Cheerios,G,C,110,3,1,250,1.5,11.5,10.0,90.0,25,1,1.00,0.75,31.072217
38,Just_Right_Crunchy__Nuggets,K,C,110,2,1,170,1.0,17.0,6.0,60.0,100,3,1.00,1.00,36.523683
42,Lucky_Charms,G,C,110,2,1,180,0.0,12.0,12.0,55.0,25,2,1.00,1.00,26.734515
44,"Muesli_Raisins,_Dates,_&_Almonds",R,C,150,4,3,95,3.0,16.0,11.0,170.0,25,3,1.00,1.00,37.136863
45,"Muesli_Raisins,_Peaches,_&_Pecans",R,C,150,4,3,150,3.0,16.0,11.0,170.0,25,3,1.00,1.00,34.139765
47,Multi-Grain_Cheerios,G,C,100,2,1,220,2.0,15.0,6.0,90.0,25,1,1.00,1.00,40.105965
56,Quaker_Oat_Squares,Q,C,100,4,1,135,2.0,14.0,6.0,110.0,25,3,1.00,0.50,49.511874
60,Raisin_Squares,K,C,90,2,0,0,2.0,15.0,6.0,110.0,25,3,1.00,0.50,55.333142
62,Rice_Krispies,K,C,110,2,0,290,0.0,22.0,3.0,35.0,25,1,1.00,1.00,40.560159
66,Smacks,K,C,110,2,1,70,1.0,9.0,15.0,40.0,25,2,1.00,0.75,31.230054
68,Strawberry_Fruit_Wheats,N,C,90,2,0,15,3.0,15.0,5.0,90.0,25,2,1.00,1.00,59.363993
69,Total_Corn_Flakes,G,C,110,2,1,200,0.0,21.0,3.0,35.0,100,3,1.00,1.00,38.839746
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.00,0.75,39.106174
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,25,1,1.00,1.00,51.592193

In [16]:
#12. Find maximum of ratings
df.rating.max()

93.704912

In [17]:
#13. Remove column fat 
df1.drop('fat',axis=1,inplace=True)
df1

,name,mfr,type,calories,protein,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Bran,N,C,70,4,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
1,100%_Natural_Bran,Q,C,120,3,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
4,Almond_Delight,R,C,110,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,250,0.0,21.0,3.0,60.0,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,140,0.0,13.0,12.0,25.0,25,2,1.0,1.00,27.753301
74,Wheat_Chex,R,C,100,3,230,3.0,17.0,3.0,115.0,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,200,3.0,17.0,3.0,110.0,25,1,1.0,1.00,51.592193
76,Wheaties_Honey_Gold,G,C,110,2,200,1.0,16.0,8.0,60.0,25,1,1.0,0.75,36.187559

In [18]:
#17. Count records for each manufacturer [mfr] 
df.groupby('mfr').mfr.value_counts()

mfr
A     1
G    22
K    23
N     6
P     9
Q     8
R     8
Name: count, dtype: int64

In [19]:
#18. Select name, calories and ratings only
df[['name','calories','rating']]

                         name  calories     rating
0                   100%_Bran        70  68.402973
1           100%_Natural_Bran       120  33.983679
2                    All-Bran        70  59.425505
3   All-Bran_with_Extra_Fiber        50  93.704912
4              Almond_Delight       110  34.384843
..                        ...       ...        ...
72                    Triples       110  39.106174
73                       Trix       110  27.753301
74                 Wheat_Chex       100  49.787445
75                   Wheaties       100  51.592193
76        Wheaties_Honey_Gold       110  36.187559

[77 rows x 3 columns]